### ISSUE TITLE
Use MySqlConnector for async I/O

### ISSUE THREAD

**Issue by bgrainger** [adamosoftware/Postulate.Orm#32]
The Query code [uses Dapper's `QueryAsync`](https://github.com/adamosoftware/Postulate.Orm/blob/62db08bac1b038df0d91c445a07a36d7bd344468/Core/Query.cs#L153), which will call `DbConnection.ExecuteReaderAsync`. It's a long-standing bug in MySql.Data ([bug 70111](https://bugs.mysql.com/bug.php?id=70111)) that the async I/O methods are not implemented; thus all these methods will fall back to running synchronously. (See also [here](https://stackoverflow.com/a/42305108/) and [here](https://stackoverflow.com/questions/30551459/mysql-c-sharp-async-methods-doesnt-work) on Stack Overflow.)

To fix this, you could switch to https://github.com/mysql-net/MySqlConnector, an OSS replacement for MySql.Data that supports true asynchronous I/O.

If you're interested in this, I'd be happy to open a PR.

**Comment by adamosoftware** [comment]
wow -- thank you. I like what you're doing, but I don't really want to swap out the MySql.Data dependency right now. My team at work wouldn't dig it. We're not doing any async queries as it turns out, so it hasn't mattered. Your library looks impressive though, so I may circle back with you at some point!
